import AdaCrowd.Measure
import Mathlib.Analysis.Calculus.Gradient.Basic

/-! General probability-space statement of the TPAMI optimization results. -/

open MeasureTheory
open scoped BigOperators RealInnerProductSpace

noncomputable section

namespace AdaCrowd.General

variable {Ω E : Type*} [mΩ : MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]
variable [NormedAddCommGroup E] [InnerProductSpace ℝ E] [CompleteSpace E]

/-- A1--A3, SGD dynamics, and the regularity needed to interpret expectations.
`biasVector` is the subset gradient minus the full gradient; `noise` is the
stochastic gradient minus the subset gradient. -/
structure StochasticRun (μ : Measure Ω) (T : ℕ) (F : E → ℝ) (grad : E → E)
    (L eta sigma2 lower : ℝ) where
  /-- The sigma-algebra generated by the current iterate and acquired subset,
  or a larger history for which A2 holds. Monotonicity is not needed. -/
  info : ℕ → MeasurableSpace Ω
  info_le : ∀ t, info t ≤ mΩ
  state : ℕ → Ω → E
  fullGradient : ℕ → Lp E 2 μ
  biasVector : ℕ → Lp E 2 μ
  noise : ℕ → Lp E 2 μ
  epsilon : ℕ → Ω → ℝ
  initialPoint : E
  initial : ∀ᵐ ω ∂μ, state 0 ω = initialPoint
  horizon_pos : 0 < T
  smoothness_pos : 0 < L
  eta_pos : 0 < eta
  eta_le : eta ≤ 1 / L
  lower_bound : ∀ x, lower ≤ F x
  gradient_is_gradient : ∀ x, HasGradientAt F (grad x) x
  smooth : SmoothUpperModel F grad L
  objective_integrable : ∀ t ≤ T, Integrable (fun ω => F (state t ω)) μ
  epsilon_integrable : ∀ t < T, Integrable (fun ω => epsilon t ω ^ 2) μ
  gradient_matches : ∀ t < T, ∀ᵐ ω ∂μ, fullGradient t ω = grad (state t ω)
  gradient_adapted : ∀ t < T, AEStronglyMeasurable[info t] (fullGradient t) μ
  bias_adapted : ∀ t < T, AEStronglyMeasurable[info t] (biasVector t) μ
  update : ∀ t < T, ∀ᵐ ω ∂μ, state (t + 1) ω = state t ω - (eta / Real.sqrt T) •
    (fullGradient t ω + biasVector t ω + noise t ω)
  unbiased : ∀ t < T, μ[(fun ω => noise t ω) | info t] =ᵐ[μ] 0
  variance : ∀ t < T, (∫ ω, ‖noise t ω‖ ^ 2 ∂μ) ≤ sigma2
  bias : ∀ t < T, ∀ᵐ ω ∂μ, ‖biasVector t ω‖ ≤ epsilon t ω

namespace StochasticRun

variable {T : ℕ} {F : E → ℝ} {grad : E → E} {L eta sigma2 lower : ℝ}
variable (A : StochasticRun μ T F grad L eta sigma2 lower)

def objective (t : ℕ) : ℝ := ∫ ω, F (A.state t ω) ∂μ
def gradSq (t : ℕ) : ℝ := ∫ ω, ‖grad (A.state t ω)‖ ^ 2 ∂μ
def biasSq (t : ℕ) : ℝ := ∫ ω, A.epsilon t ω ^ 2 ∂μ

theorem descent (t : ℕ) (ht : t < T) :
    A.objective (t + 1) ≤ A.objective t - (eta / Real.sqrt T) / 2 * A.gradSq t
      + (eta / Real.sqrt T) / 2 * A.biasSq t
      + L * (eta / Real.sqrt T) ^ 2 / 2 * sigma2 := by
  have hs := sqrt_step_admissible A.horizon_pos A.smoothness_pos A.eta_pos A.eta_le
  have hsm : ∀ᵐ ω ∂μ, F (A.state (t + 1) ω) ≤ F (A.state t ω)
      - (eta / Real.sqrt T) * ⟪A.fullGradient t ω,
          A.fullGradient t ω + A.biasVector t ω + A.noise t ω⟫
      + L * (eta / Real.sqrt T) ^ 2 / 2 *
          ‖A.fullGradient t ω + A.biasVector t ω + A.noise t ω‖ ^ 2 := by
    filter_upwards [A.gradient_matches t ht, A.update t ht] with ω hg hu
    have hd := smooth_update A.smooth (le_of_lt hs.1) (A.state t ω)
      (A.fullGradient t ω + A.biasVector t ω + A.noise t ω)
    rwa [← hg, ← hu] at hd
  have hd := expected_descent (A.info_le t) (A.fullGradient t) (A.biasVector t) (A.noise t)
    (A.gradient_adapted t ht) (A.bias_adapted t ht) (A.unbiased t ht)
    (A.objective_integrable t (Nat.le_of_lt ht))
    (A.objective_integrable (t + 1) (Nat.succ_le_of_lt ht)) (A.epsilon_integrable t ht)
    (le_of_lt A.smoothness_pos) (le_of_lt hs.1) hs.2 (A.variance t ht) (A.bias t ht) hsm
  have hg : (∫ ω, ‖A.fullGradient t ω‖ ^ 2 ∂μ) = A.gradSq t := by
    apply integral_congr_ae
    filter_upwards [A.gradient_matches t ht] with ω hω
    rw [hω]
  rwa [hg] at hd

/-- General probability-space version of the sharper coefficient-1 bound. -/
theorem stationarity_sharp :
    (∑ t ∈ Finset.range T, A.gradSq t) / T ≤
      2 * (F A.initialPoint - lower) / (eta * Real.sqrt T)
        + L * eta * sigma2 / Real.sqrt T
        + (∑ t ∈ Finset.range T, A.biasSq t) / T := by
  have hl : lower ≤ A.objective T := by
    have hi := integral_mono_ae (integrable_const lower) (A.objective_integrable T le_rfl)
      (Filter.Eventually.of_forall (fun ω => A.lower_bound (A.state T ω)))
    simpa [objective] using hi
  have hi : A.objective 0 = F A.initialPoint := by
    calc
      A.objective 0 = ∫ _ : Ω, F A.initialPoint ∂μ := by
        apply integral_congr_ae
        filter_upwards [A.initial] with ω hω
        rw [hω]
      _ = F A.initialPoint := by simp
  have hb := sqrt_step_stationarity A.horizon_pos A.eta_pos A.descent hl
  rwa [hi] at hb

/-- The exact displayed stationarity bound in the manuscript. -/
theorem stationarity :
    (∑ t ∈ Finset.range T, A.gradSq t) / T ≤
      2 * (F A.initialPoint - lower) / (eta * Real.sqrt T)
        + L * eta * sigma2 / Real.sqrt T
        + 2 / T * (∑ t ∈ Finset.range T, A.biasSq t) := by
  have hn : 0 ≤ ∑ t ∈ Finset.range T, A.biasSq t :=
    Finset.sum_nonneg (fun t _ => integral_nonneg (fun ω => sq_nonneg (A.epsilon t ω)))
  have hTr : (0 : ℝ) < T := by exact_mod_cast A.horizon_pos
  have hb := A.stationarity_sharp
  have hp := div_nonneg hn (le_of_lt hTr)
  calc
    _ ≤ 2 * (F A.initialPoint - lower) / (eta * Real.sqrt T)
        + L * eta * sigma2 / Real.sqrt T
        + 2 * ((∑ t ∈ Finset.range T, A.biasSq t) / T) := by linarith
    _ = _ := by ring

/-- Explicit finite-horizon bias floor, avoiding ambiguity in O notation. -/
theorem uniform_bias_floor {epsilonBar : ℝ}
    (hbias : (∑ t ∈ Finset.range T, A.biasSq t) / T ≤ epsilonBar ^ 2) :
    (∑ t ∈ Finset.range T, A.gradSq t) / T ≤
      2 * (F A.initialPoint - lower) / (eta * Real.sqrt T)
        + L * eta * sigma2 / Real.sqrt T + 2 * epsilonBar ^ 2 := by
  have hb := A.stationarity
  have he : 2 / (T : ℝ) * (∑ t ∈ Finset.range T, A.biasSq t) =
      2 * ((∑ t ∈ Finset.range T, A.biasSq t) / T) := by ring
  rw [he] at hb
  linarith

/-- Random budgets: the reciprocal subset size is inside the expectation. -/
theorem budget_bias_random (budget : ℕ → Ω → ℕ) {c : ℝ}
    (_hc : 0 < c) (_hbudget : ∀ t < T, ∀ᵐ ω ∂μ, 0 < budget t ω)
    (hreciprocal : ∀ t < T, Integrable (fun ω => 1 / (budget t ω : ℝ)) μ)
    (hbias : ∀ t < T, ∀ᵐ ω ∂μ, A.epsilon t ω ^ 2 ≤ c ^ 2 / budget t ω) :
    (∑ t ∈ Finset.range T, A.gradSq t) / T ≤
      2 * (F A.initialPoint - lower) / (eta * Real.sqrt T)
        + L * eta * sigma2 / Real.sqrt T
        + (2 * c ^ 2 / T) *
          (∑ t ∈ Finset.range T, ∫ ω, 1 / (budget t ω : ℝ) ∂μ) := by
  have hmean : ∀ t < T, A.biasSq t ≤ c ^ 2 * (∫ ω, 1 / (budget t ω : ℝ) ∂μ) := by
    intro t ht
    have hr : Integrable (fun ω => c ^ 2 / (budget t ω : ℝ)) μ := by
      simpa [div_eq_mul_inv] using (hreciprocal t ht).const_mul (c ^ 2)
    have hi := integral_mono_ae (A.epsilon_integrable t ht) hr (hbias t ht)
    simpa only [biasSq, div_eq_mul_inv, one_mul, integral_const_mul] using hi
  have hs := Finset.sum_le_sum (fun t ht => hmean t (Finset.mem_range.mp ht))
  rw [← Finset.mul_sum] at hs
  have hTr : (0 : ℝ) < T := by exact_mod_cast A.horizon_pos
  have hm := mul_le_mul_of_nonneg_left hs (show 0 ≤ 2 / (T : ℝ) by positivity)
  have hb := A.stationarity
  calc
    _ ≤ 2 * (F A.initialPoint - lower) / (eta * Real.sqrt T)
        + L * eta * sigma2 / Real.sqrt T
        + 2 / T * (c ^ 2 * (∑ t ∈ Finset.range T, ∫ ω, 1 / (budget t ω : ℝ) ∂μ)) := by
          linarith
    _ = _ := by ring

/-- Deterministic subset sizes give the manuscript's budget-bias expression. -/
theorem budget_bias (budget : ℕ → ℕ) {c : ℝ}
    (hc : 0 < c) (hbudget : ∀ t < T, 0 < budget t)
    (hbias : ∀ t < T, ∀ᵐ ω ∂μ, A.epsilon t ω ^ 2 ≤ c ^ 2 / budget t) :
    (∑ t ∈ Finset.range T, A.gradSq t) / T ≤
      2 * (F A.initialPoint - lower) / (eta * Real.sqrt T)
        + L * eta * sigma2 / Real.sqrt T
        + (2 * c ^ 2 / T) * (∑ t ∈ Finset.range T, 1 / (budget t : ℝ)) := by
  simpa using A.budget_bias_random (fun t _ => budget t) hc
    (fun t ht => Filter.Eventually.of_forall (fun _ => hbudget t ht))
    (fun t _ => integrable_const _) hbias

end StochasticRun
end AdaCrowd.General
